title: Dai Pham's Blog
logo: /assets/img/logo.jpg
base_url: https://daipham1210.github.io
description: I'm Dai Pham from Viet Nam. I love programming, as well as running, taking photos and learning new thing. Feel free to get in touch or take a look at my blog posts :)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
collections:
  posts:
    output: true