title: Dai Pham's Blog
logo: /assets/img/logo.jpg
base_url: https://daipham1210.github.io
description: Tôi xuất thân con nhà vẽ, nhưng thích đi code. Hiện tôi đang làm kĩ sư mặt tiền cho một tập đoàn tài chính ở thung lũng túi nâng silicon.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
